name: VTK9 C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install packages 
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libglvnd-dev libproj-dev libvtk9-dev libvtk9-qt-dev 
    - name: Check installed versions
      run: cmake --version 
    - name: Configure Simple
      run:  mkdir build && cd build && cmake -DTESTDICOM2MESH=ON -DTESTDICOM2MESHLIB=ON -DBUILD_GUI=OFF -DUSE_VTK_DICOM=OFF ..
    - name: Build D2M Simple
      run: cd build && make
    - name: Run Test Simple
      run: ./build/lib/runLibTests && ./build/dicom2mesh/runD2MTests

    - name: Clean
      run: rm -rf build


